plugins {
    id 'java'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

ext {
    mindustryVersion = 'v159.7'
}

repositories {
    mavenCentral()
    ivy {
        url 'https://github.com/'
        patternLayout {
            artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'
        }
        metadataSources { artifact() }
        content { includeVersion('Anuken', 'Mindustry', mindustryVersion) }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly "Anuken:Mindustry:$mindustryVersion"
}

jar {
    archiveFileName = 'IMindustryDesktop.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
    from('mod.hjson')
}

tasks.register('deploy') {
    dependsOn jar
    doLast {
        // This will be handled in the workflow with Android SDK
        copy {
            from 'build/libs/IMindustryDesktop.jar'
            into 'build/libs'
            rename { 'IMindustry.jar' }
        }
    }
}
